import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { FlatCompat } from '@eslint/eslintrc'

const __dirname = dirname(fileURLToPath(import.meta.url))
const compat = new FlatCompat({ baseDirectory: __dirname })

const eslintConfig = [
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'playwright-report/**',
      'test-results/**',
      'out/**',
      '.cache/**',
      // Generated by `next dev/build` — not ours to lint.
      'next-env.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      // docs/14 §1 — no floating promises, no unsafe any leakage.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // docs/14 §5 — the service-role client is restricted to apply route, integration callbacks, cron.
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@/lib/supabase/service'],
              message:
                'Service-role client bypasses RLS (docs/03 §Rules). Only the apply route, integration callbacks, and cron may import it.',
            },
          ],
        },
      ],
    },
  },
  {
    // docs/14 §5 — the allowed service-client zones (docs/03 §Rules):
    // public apply surface, integration callbacks, cron, signed webhooks.
    files: [
      'src/app/api/apply/**',
      'src/app/api/jobs/**/public/**',
      'src/app/api/integrations/**',
      'src/app/api/cron/**',
      'src/app/api/webhooks/**',
      'src/app/(public)/**',
    ],
    rules: {
      'no-restricted-imports': 'off',
    },
  },
]

export default eslintConfig
